// UI Components
// import NavBar from "@/components/NavBar/NavBar";
import CardLayout from "@/components/CardLayout/CardLayout";

// Styles
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Scott Cook | Flag Filter Fun</title>
      <body className={inter.className}>
        <CardLayout />
      </body>
    </html>
  );
}
